### ISSUE TITLE
hjoin (Python) crashes if it can't talk to hatcogd (Go)

### ISSUE THREAD

**Issue by grahamking** [grahamking/hatcog#12]
If `hjoin` can't connect to `hatcogd`, it can segfault (yes the Python part seg faults). Stack trace in log is:

```
2012-09-04 09:31:45,652 INFO: Connecting to daemon
2012-09-04 09:31:45,659 ERROR: Could not connect
Traceback (most recent call last):
File "/usr/local/lib/python3.2/dist-packages/hatcog-0.9-py3.2.egg/hjoin/hjoin.py", line 606, in get_daemon_connection
    sock = socket.create_connection((host.encode("utf8"), int(port)))
File "/usr/lib/python3.2/socket.py", line 404, in create_connection
    raise err
File "/usr/lib/python3.2/socket.py", line 395, in create_connection
    sock.connect(sa)
socket.error: [Errno 111] Connection refused
2012-09-04 09:31:45,662 DEBUG: Starting daemon: start-stop-daemon --start --background --exec /usr/local/bin/hatcogd-64 -- -host=127.0.0.1 -port=8790 --logdir /home/graham/.hatcog/
```

**Comment by grahamking** [comment]
server.log prints: `Error connecting to IRC server:dial tcp 193.219.128.49:6697: connection timed out`

I think this is same problem. Server might not be accepting client connections until it has an IRC server connection.
