### ISSUE TITLE
hjoin crashes,    File "/usr/local/lib/python3.5/dist-packages/hatcog-0.10-py3.5.egg/hjoin/hjoin.py", line 68, in main

### ISSUE THREAD

**Issue by evanescente-ondine** [grahamking/hatcog#18]
Just installed from git, but haven't yet edited the config file. Still, see the result. Betcha it's not normal.

=> hjoin freenode.tmux  
hatcog v0.10 (github.com/grahamking/hatcog) logging to /home/mehdi/.hatcog/client.log
Traceback (most recent call last):
  File "/usr/local/bin/hjoin", line 11, in <module>
    load_entry_point('hatcog==0.10', 'console_scripts', 'hjoin')()
  File "/usr/local/lib/python3.5/dist-packages/hatcog-0.10-py3.5.egg/hjoin/hjoin.py", line 68, in main
  File "/usr/lib/python3.5/logging/__init__.py", line 1745, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.5/logging/__init__.py", line 1009, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mehdi/.hatcog/client.log'

**Comment by grahamking** [comment]
Thanks for the report. You need to create directory `/home/mehdi/.hatcog`

It should probably warn you about that, or create it for you.

**Comment by nnsite** [comment]
Ok. I created it, re-execute hjoin, then:

gpg: WARNING: unsafe permissions on homedir '/home/mehdi/.gnupg'
gpg: can't open 'pw_file.asc': Aucun fichier ou dossier de ce type
gpg: decrypt_message failed: Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hatcog-0.10-py3.5.egg/hjoin/hjoin.py",
line 111, in main
  File "/usr/local/lib/python3.5/dist-packages/hatcog-0.10-py3.5.egg/hjoin/hjoin.py",
line 161, in __init__
  File "/usr/local/lib/python3.5/dist-packages/hatcog-0.10-py3.5.egg/hjoin/hjoin.py",
line 568, in get_password
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['gpg', '-d', 'pw_file.asc']'
returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hjoin", line 11, in <module>
    load_entry_point('hatcog==0.10', 'console_scripts', 'hjoin')()
  File "/usr/local/lib/python3.5/dist-packages/hatcog-0.10-py3.5.egg/hjoin/hjoin.py",
line 124, in main
UnboundLocalError: local variable 'client' referenced before assignment

**Comment by grahamking** [comment]
You need to customize `.hatcogrc` to setup the IRC accounts you use. Change [this line](https://github.com/grahamking/hatcog/blob/master/.hatcogrc#L30) to delete `$(gpg -d pw_file.asc)`. Also delete these lines https://github.com/grahamking/hatcog/blob/master/.hatcogrc#L32-L42 .

**Comment by grahamking** [comment]
Note that I haven't worked on hatcog in 4.5 years. I'm glad you're trying it, and I'm happy to help, but I don't promise it will work. You will probably need to have some experience programming in Python to succeed.
