### ISSUE TITLE
BUG: Resizing the window in tmux kills hjoin

### ISSUE THREAD

**Issue by grahamking** [grahamking/hatcog#4]
After shrinking the window, type in the input box until reaching the edge of the screen. Crash!

Stack trace:

```
Traceback (most recent call last):
  File "/home/graham/bin/hjoin", line 80, in main
    client.run()
  File "/home/graham/bin/hjoin", line 154, in run
    self.act_server(sock_data)
  File "/home/graham/bin/hjoin", line 181, in act_server
    display = translate_in(msg, self)
  File "/home/graham/Projects/hatcog/hjoin/hfilter.py", line 144, in translate_in
    retval = getattr(callbacks, func_name)(obj)
  File "/home/graham/bin/hjoin", line 227, in on_join
    self.terminal.set_users(self.users.count())
  File "/home/graham/Projects/hatcog/hjoin/term.py", line 259, in set_users
    self._display_user_count()
  File "/home/graham/Projects/hatcog/hjoin/term.py", line 274, in _display_user_count
    self.win_status.addstr(0, right_pos, msg)
error: addstr() returned ERR
```

It seems to happens when we shrink the window, and try and add text beyond the edge of it, before hjoin knows it has been resized.

Need to get a reproduce-able test case. Fix might be to catch the error and call rebuild.

**Comment by grahamking** [comment]
Haven't seen this in ages. Closing.
